#!/bin/bash
help_text="
NAME
  gen_ora_web_pgs - Creates web pages for Oracle scripts

USAGE
  gen_ora_web_pgs

DESCRIPTION
  Creates web pages for Oracle scripts.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Creates web pages for Oracle scripts"

rm -f /c/MJN/drive/github/mjnurse-github-io/Other-O/Oracle/Script*

cd /c/MJN/drive/github/oracle

for f in $(grep -l "^-- web_desc_line" *.sql); do

   dl="$(grep '^-- web_desc_line' $f | sed 's/-- web_desc_line: *//; s/ *$//')"
   dest=$(echo "/c/MJN/drive/github/mjnurse-github-io/Other-O/Oracle/Script $f - $dl.md" | sed "s/ /_/g")

   echo "---" > $dest
   echo "title: $f - $dl" >> $dest
   echo "---" >> $dest
   echo "" >> $dest
   echo "\`\`\`sql" >> $dest
   cat $f >> $dest
   echo "\`\`\`" >> $dest

   echo $dest

   fdr="$(date -r $f)"
   touch -d "$fdr" $dest
done

