#!/bin/bash
help_text="
NAME
  gen_bash_web_pgs - Creates webs pages for bash scripts

USAGE
  gen_bash_web_pgs

DESCRIPTION
  Creates webs pages for bash scripts.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Creates webs pages for bash scripts"

rm -f /c/MJN/drive/github/mjnurse-github-io/LinuxBash-L/Script*

cd /c/MJN/drive/github/bash
for f in $(grep -l "^web_desc_line" *); do

  dl="$(grep -m1 '^web_desc_line=' $f | sed 's/web_desc_line=*//; s/ *$//; s/"//g')"

  dest=$(echo "/c/MJN/drive/github/mjnurse-github-io/LinuxBash-L/Script $f - $dl.md" | sed "s/ /_/g")

  echo dest_file: $dest

  echo "---" > $dest
  echo "title: $f - $dl" >> $dest
  echo "---" >> $dest
  echo "" >> $dest
  echo "\`\`\`bash" >> $dest
  cat $f >> $dest
  echo "\`\`\`" >> $dest

  fdr="$(date -r $f)"
  touch -d "$fdr" $dest
done

# Create bash script packs and pack pages

rm -f /c/MJN/drive/github/mjnurse-github-io/LinuxBash-L/Linux_bash*Pack.md

for p in default; do
  file_list="$(grep -l "^pack_member.*default" *)"
  pack -s -f -n ${p} ${file_list}

  dest="/c/MJN/drive/github/mjnurse-github-io/LinuxBash-L/Linux_bash_${p}_pack.md"

  echo
  echo pack-file: $dest
  echo pack-file: $file_list

  echo "---" > $dest
  echo "title: Linux bash $p Pack" >> $dest
  echo "---" >> $dest
  echo "" >> $dest
  echo "Packs contain bash scripts which have been compressed and converted to a" >> $dest
  echo "base64 string.  This is a convenient wat to copy a set of bash scripts" >> $dest
  echo "into a linux environment using only a command line terminal." >> $dest
  echo "" >> $dest
  echo "<script>" >> $dest
  echo "  let packText=\`$(cat ${p}.pack)" >> $dest
  echo "\`;" >> $dest
  echo "</script>" >> $dest
  echo "" >> $dest
  echo "## Contents" >> $dest
  echo "\`\`\`" >> $dest
  h -m $file_list >> $dest
  echo "\`\`\`" >> $dest
  echo "" >> $dest
  echo "<button onCLick='copyToClipboard(packText)'>Copy To Clipboard</button>" >> $dest
  echo "" >> $dest
  echo "\`\`\`bash" >> $dest
  cat ${p}.pack >> $dest
  echo "\`\`\`" >> $dest

done

